### PR TITLE
docs: correct cmu link, add lodash link

### PR DESCRIPTION
**Pull request by ChristianMurphy**

### CODE REVIEW

**Comment by zeke** [comment]
Thanks!

**Comment by zeke** [comment]
Are you using this project for anything fun?

**Comment by ChristianMurphy** [comment]
Exploring using this or metaphone to automatically detect rhyming schemes in poetry.

**Comment by ChristianMurphy** [comment]
https://github.com/ChristianMurphy/classify-poetry

**Comment by zeke** [comment]
Wow that's really interesting. I've long dreamed of making a gameified website to collect more rhymes from humans, to build upon the CMU corpus.

**Comment by zeke** [comment]
I'll get a release of this out soon. See https://github.com/words/rhymes/pull/2#issuecomment-444291503

**Pull request merged**
