### PR TITLE
fix: upgraded some dependencies and added .node-version files

### PR DESCRIPTION
**Pull request by agent-0028**
Thanks for this really fun library.

I did some upgrades to make the automatic security scanning robots happy!

Let me know if you want any tweaks and I'll get to 'em as soon as I can.

### CODE REVIEW

**Comment by zeke** [comment]
Wow the semantic-release worked! ☝️

**Comment by zeke** [comment]
PS thanks for the pull request. Glad you're finding this useful (or at least fun) 💛

**Comment by agent-0028** [comment]
You are most welcome! I used this fun repo in an example application that deploys a Node.js Lambda to AWS. Those darn GitHub security warnings drove me to fork and upgrade before I published this post, glad you were able to pick up the change! Just switched back to installing from you instead of my fork and all seems good.

https://blog.testdouble.com/posts/2019-11-26-from-noops-to-allops/

**Comment by zeke** [comment]
Nice! Thanks for sharing.

**Pull request merged**
